workflows:
  ios-workflow:
    name: iOS Build
    environment:
      xcode: latest
      cocoapods: default
      flutter: stable
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Clean previous builds and pods
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod cache clean --all
      - name: Set iOS Deployment Target to 13.0
        script: |
          cd ios
          sed -i '' 's/platform :ios, .*$/platform :ios, '13.0'/' Podfile
          cat Podfile  # This is optional, to view the changes made
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --repo-update
      - name: Set Xcode build settings (Non-modular includes)
        script: |
          cd ios
          xcrun xcodebuild -workspace Runner.xcworkspace -scheme Runner \
            -configuration Release \
            CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES=YES \
            VALID_ARCHS=arm64 \
            ENABLE_BITCODE=NO \
            ONLY_ACTIVE_ARCH=NO
      - name: Flutter build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa
