workflows:
  ios:
    name: iOS build
    max_build_duration: 120
    scripts:
      - name: "Install dependencies"
        script: |
          flutter pub get
          cd ios
          pod install --repo-update
          cd ..
      - name: "Allow non-modular includes"
        script: |
          echo 'post_install do |installer|' >> ios/Podfile
          echo '  installer.pods_project.targets.each do |target|' >> ios/Podfile
          echo '    target.build_configurations.each do |config|' >> ios/Podfile
          echo '      config.build_settings["CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES"] = "YES"' >> ios/Podfile
          echo '    end' >> ios/Podfile
          echo '  end' >> ios/Podfile
          echo 'end' >> ios/Podfile
      - name: "Build iOS app"
        script: |
          flutter build ios --no-codesign
    artifacts:
      - build/ios/ipa
