// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgU52gE-of9tEbcxJ-cUB9E6TMt_IAzRU',
    appId: '1:1047331650888:web:d1d35acc9a8e723fed477d',
    messagingSenderId: '1047331650888',
    projectId: 'shepherd-1f1c9',
    authDomain: 'shepherd-1f1c9.firebaseapp.com',
    storageBucket: 'shepherd-1f1c9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4-9XsLmw5oOnR9A3uwevMN7KrzbOS1Bk',
    appId: '1:1047331650888:android:797923b3a2246a26ed477d',
    messagingSenderId: '1047331650888',
    projectId: 'shepherd-1f1c9',
    storageBucket: 'shepherd-1f1c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkKZof8Uq7Y2Df1-cIfaFNwr3AWIM5y5k',
    appId: '1:1047331650888:ios:b94864014cbe3cd2ed477d',
    messagingSenderId: '1047331650888',
    projectId: 'shepherd-1f1c9',
    storageBucket: 'shepherd-1f1c9.appspot.com',
    iosBundleId: 'com.example.shepherdMo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkKZof8Uq7Y2Df1-cIfaFNwr3AWIM5y5k',
    appId: '1:1047331650888:ios:b94864014cbe3cd2ed477d',
    messagingSenderId: '1047331650888',
    projectId: 'shepherd-1f1c9',
    storageBucket: 'shepherd-1f1c9.appspot.com',
    iosBundleId: 'com.example.shepherdMo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgU52gE-of9tEbcxJ-cUB9E6TMt_IAzRU',
    appId: '1:1047331650888:web:c9d27dd8fe4deb59ed477d',
    messagingSenderId: '1047331650888',
    projectId: 'shepherd-1f1c9',
    authDomain: 'shepherd-1f1c9.firebaseapp.com',
    storageBucket: 'shepherd-1f1c9.appspot.com',
  );

}